
tasks:
  - init: |
      cd hello-world && npm install
  - command: |
      cd hello-world
      npm run dev

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - Vue.volar